version: "2"

services:
  web:
    image: nginx:1.13.1
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www/html/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./log/web/:/var/log/nginx/
    links:
      - fpm
      - db
    restart: always

  fpm:
    build: fpm/
    volumes:
      - ./www/:/var/www/html/
    links:
      - db
    restart: always

  db:
    image: mariadb:10.3.0
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3014:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=some_pw
      - MYSQL_DATABASE=some_db
      - MYSQL_USER=some_user
      - MYSQL_PASSWORD=some_pw
    restart: always
